#!/bin/bash

# Función para mostrar mensajes con formato
echo_formatted() {
  echo -e "\033[1;34m$1\033[0m"
}

# Actualizar y preparar el sistema para OMV
echo_formatted "[1/3] Actualizando y preparando el sistema..."
sudo apt-get update
sudo apt-get upgrade -y
wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/preinstall | sudo bash

# Reiniciar el sistema
echo_formatted "[2/3] Reiniciando el sistema..."
sudo reboot

# Nota al usuario
echo_formatted "[3/3] Una vez que el sistema haya reiniciado, ejecuta el siguiente comando:"
echo "wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash"
